### PR TITLE
Also look up for icons in usr/share/icons/hicolor/scalable/apps/

### PR DESCRIPTION
**Pull request by lephilousophe**
SVGs are traditionally stored in /usr/share/icons/hicolor/scalable/apps/ so this makes sense to look up for icons in this folder too.

### CODE REVIEW

**Comment by probonopd** [comment]
Thing is, it is way easier for thumbnailers to parse/show png rather than svg. So I am not entirely sure whether we should allow svg icons. But I guess since the existing code says `supportedIconExtensions := []string{".png", ".xpm", ".svg"}` I guess I should merge this for now.

**Comment by probonopd** [comment]
Maybe we should at least print a warning if if only a SVG but no PNG is found, letting the user know that a PNG should be used.

**Comment by lephilousophe** [comment]
I must admit that in ScummVM we don't use a PNG on linux only a SVG icon.
By looking at [Icon Theme Specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html), I see that SVG is optional and XPM is deprecated so, yes, warnings may be useful.
I will add them.

**Comment by lephilousophe** [comment]
And done.

**Comment by probonopd** [comment]
Thanks @lephilousophe

**Pull request merged**
