### PR TITLE
Quick fix for failing builds

### PR DESCRIPTION
**Pull request by CalebQ42**
The build will still fail since the build script is still pulling from the main repo.

This can be reverted once [otiai10/copy](https://github.com/otiai10/copy) implements the fix.

### CODE REVIEW

**Comment by probonopd** [comment]
> The build will still fail since the build script is still pulling from the main repo.

What is the advantage of merging this, then?

**Comment by CalebQ42** [comment]
Sorry, should have been more clear. This will make the builds succeed again, but the check for the PR fails because it's pulling from the main repo.

**Comment by probonopd** [comment]
In which order should I apply your PRs? And are they already ready for being merged? Thanks a lot.

**Comment by CalebQ42** [comment]
I made this PR to be merged immediately. My other PR is not quite ready, but it's close.

**Comment by probonopd** [comment]
Fingers crossed!

**Pull request merged**
