### PR TITLE
Desktop file FUSE mount

### PR DESCRIPTION
**Pull request by CalebQ42**
- Implements the idea from #112
- Desktop files and thumbnails are now stored in `~/.cache/appimaged`
- `~/.cache/appimaged/desktop` gets fuse mounted to `~/.local/share/applications/appimaged` and should unmount when appimaged stops.
  - The mount is Read-Only. If you want to edit the desktop files, you can always edit the file in .cache
  - Could make the mount writable in the future, but I couldn't get it to work  easily and doesn't seem like it's very important.
- Default to using fuse3, but falls-back to fuse2 if it's not available.

### CODE REVIEW

**Comment by CalebQ42** [comment]
Additional fixes:

- Change build script to using stable v0.10 since the build we have been using seems to be no longer available.
- Force svg thumbnails to render at 512x512. I had an AppImage where the thumbnail was 12x12, lol.
- Fixed build instructions for the individual programs. (#230 #229)

**Comment by CalebQ42** [comment]
It seems like adding PATH to the watched directory is causing erroneous desktop notifications when the system updates.
Screenshot from 2022-12-31 17-14-30
I'm going to work on the inotify code to see if I can optimize it and detect if a file is an AppImage better.

**Comment by CalebQ42** [comment]
I ended up getting _a bit_ carried away. I ended up completely reworking fsnotify, integration and unintegration, and how volumes getting mounted or unmounted are handled.

- Changed to a different notify library that's actively supported.
- `appimaged` remember which AppImages it's integrated so when a file is deleted, we just have to see if it's already integrated.
  - A nice side effect is that removal notifications now have the proper application name.
  - Integration and unintegration should now be async safe by using `sync.Mutex` to make sure we are only doing one operation at a time.
- Only files that end with `.appimage` or `.app` and watched directories are checked.
- If a directory we are watching is deleted, all AppImages that were within are unintegrated.
  - If the directory is then re-created, they are re-added.
  - These give a grouped notification instead of notifications for each AppImage.
    - Ex: Added 2 applications from /mnt/Drive
- If a mount point is added or removed, we no longer re-check every single directory and re-runs integration on every AppImage, now only the effected mount point is checked or removed.
- Added `AppImage.Mount` to `goappimage`.
  - The AppImage must be type 2, and it uses fuse3.
- Application menus are only rebuilt a maximum of once a second (I think I broke this a while back).

**Comment by probonopd** [comment]
> The AppImage must be type 2, and it uses fuse3.

What does this mean? This introduces a libfuse3 dependency?

**Comment by CalebQ42** [comment]
It would only be for `AppImage.Mount` due to my squashfs library only using fuse3 at the moment. That being said, I had to make some changes to how my squash library handles mounts and I removed that function for now.

**Comment by probonopd** [comment]
Thanks @CalebQ42. So now this PR does not introduce a FUSE3 dependency?

**Comment by CalebQ42** [comment]
Nope! It prefers to use fuse3, but if that's not available it will use fuse2.

**Comment by CalebQ42** [comment]
Just wondering if there's any particular reason this hasn't been pulled or if it's just that you've been busy lately. I noticed you've been working on helloSystem and it recently has a major release, so I'm guessing it's that, but just wanted to make sure. Not angry or anything, just curious.

**Comment by probonopd** [comment]
Indeed @CalebQ42. Been busy, that's the main reason. Another reason is that I am a bit doubtful about the use of FUSE in general since distributions dropped libfuse2 from one day to the next when I was hoping that one could rely on libfuse2 just being there forever.

**Comment by CalebQ42** [comment]
How I see it is that AppImage requires FUSE anyway so we know it's present on the system if appimaged is running at all. For that to change it would take a lot of work. Considering that both Snap and Flatpak also use FUSE and I don't think it's going anywhere anytime soon.

That being said, I'd be more then happy to separate out the bug fixes and improvements so they can be pulled in.

**Comment by CalebQ42** [comment]
I'm going to separate this PR out into general fixes / improvements and FUSE

**Pull request closed without merging**
