### PR TITLE
Add Version to AppImage struct

### PR DESCRIPTION
**Pull request by mgord9518**
Pull the version out of the AppImage desktop file, perferring X-AppImage-Version since a lot of people are lazy and don't fill out the normal Version key correctly.

### CODE REVIEW

**Comment by probonopd** [comment]
Hello @mgord9518, I'd happily consider your PR but `Version=` should not be used, not even as a fallback, because it describes the version of the format used for the desktop file itself rather than the version of the application. This comes from the [XDG Desktop Spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/) which has no standard way to describe the application version.

**Comment by mgord9518** [comment]
Oh thank you! I'll resubmit without falling back to "Version", I guess I probably should've looked it up before assuming what it meant

**Comment by mgord9518** [comment]
I've updated the PR

**Comment by probonopd** [comment]
Thank you very much.

**Pull request merged**
