### PR TITLE
Fixes #251

### LINKED ISSUE #251: appimaged exiting with code=1
`journalctl --user -u appimaged.service`
```апр 14 13:28:41 Lenovo-Mike systemd[1840]: Started AppImage system integration daemon.
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: appimaged-765-x86_64.AppImage 119
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: 2023/04/14 13:28:42 main: PATH: /tmp/.mount_appimaLLnJmA/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/mike/opt/cmake/bin/:/snap/bin:/opt/node-v15.8.0-linux-x64/bin:/opt/phantomjs-2.1.1-linux-x86_64/bin
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: This process based on /proc/self/exe: /tmp/.mount_appimaLLnJmA/usr/bin/appimaged
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: Terminating other running processes with that name...
апр 14 13:28:42 Lenovo-Mike dbus-daemon[282209]: [session uid=1000 pid=282206] AppArmor D-Bus mediation is enabled
апр 14 13:28:42 Lenovo-Mike dbus-daemon[282209]: [session uid=1000 pid=282206] Activating service name='org.freedesktop.systemd1' requested by ':1.0' (uid=1000 pid=282173 comm="/home/mike/????????????????/appimaged-765-x86_64.A" label="unconfined")
апр 14 13:28:42 Lenovo-Mike dbus-daemon[282209]: [session uid=1000 pid=282206] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: ERROR pre: checkIfSystemdServiceRunning: Process org.freedesktop.systemd1 exited with status 1
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: 2023/04/14 13:28:42 Deleted 0 desktop files from /home/mike/.local/share/applications/; use -v to see details
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: 2023/04/14 13:28:42 Launched by systemd: LAUNCHED_BY_SYSTEMD is present
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: ERROR MQTT: network Error : EOF
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: 2023/04/14 13:28:42 MQTT client connected: false
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: 2023/04/14 13:28:42 main: Running from /tmp/.mount_appimaLLnJmA/usr/bin
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: 2023/04/14 13:28:42 main: xdg.DataHome = /home/mike/.local/share
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: 2023/04/14 13:28:42 Overwrite: false
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: 2023/04/14 13:28:42 Clean: false
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: map[inode64: mode:755 nr_inodes:945723 rw: size:3782892k]
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: map[gid:5 mode:620 ptmxmode:000 rw:]
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: map[inode64: mode:755 rw: size:769672k]
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: map[errors:remount-ro rw:]
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: map[inode64: rw:]
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: map[inode64: rw: size:5120k]
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: map[pagesize:2M rw:]
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: map[rw:]
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: map[mode:700 rw:]
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: map[rw:]
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: map[rw:]
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: map[rw:]
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: map[rw:]
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: map[gid:1000 inode64: mode:700 nr_inodes:192418 rw: size:769672k uid:1000]
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: map[group_id:1000 rw: user_id:1000]
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: map[group_id:1000 rw: user_id:1000]
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: map[lowerdir:/var/lib/docker/overlay2/l/J7YLKWBXVLIZRSIW7R5W7JLP33:/var/lib/docker/overlay2/l/DOBWOWAHPLE72YHRKUOWE55U2H:/var/lib/docker/overlay2/l/RNWBOJD5S23IISOW57NOYXOMKU:/var/lib/docker/overlay2/l/2OJI4LQL4WSPICGY2DCAOWPSVS:/var/lib/docker/overlay2/l/OCHI2K2JTTYHW7KGCPBPIM44GT:/var/lib/docker/overlay2/l/KVIAZRRLHBQJJDQ37UQ5DWT6QH:/var/lib/docker/overlay2/l/VRD2JIWRDYKGO5452THXRNJCTO:/var/lib/docker/overlay2/l/JRS32GKP53TFT6UB7WU3OGDHOX:/var/lib/docker/overlay2/l/3MBPWPHKWRISMIOSHN6GVWSUG6:/var/lib/docker/overlay2/l/2PNTINFYHBPO6ZVO6M3HWM2EY2:/var/lib/docker/overlay2/l/PRTWZDKCC6VOU5UFNBLHCLUX73:/var/lib/docker/overlay2/l/YI2LNF64YHLWF6YON54ROS2OO3:/var/lib/docker/overlay2/l/VUHZ2HTJ2FIRIO3QE36F4VIDXF:/var/lib/docker/overlay2/l/RD27FULXVIBWNYRWWVGY5POUUH:/var/lib/docker/overlay2/l/XMWFDW6P7V3ZD4ZXOFSTF3JUGQ rw: upperdir:/var/lib/docker/overlay2/69c72adcfe5bb11ce2f51306c13e399b54e9d6e600a6aab8c7bf06a5ccbd6e6f/diff workdir:/var/lib/docker/overlay2/69c72adcfe5bb11ce2f51306c13e399b54e9d6e600a6aab8c7bf06a5ccbd6e6f/work]
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: map[rw:]
апр 14 13:28:42 Lenovo-Mike appimaged-765-x86_64.AppImage[282173]: 2023/04/14 13:28:42 zeroconf: Failed to initialize resolver: listen udp6 [ff02::]:5353: socket: address family not supported by protocol
апр 14 13:28:42 Lenovo-Mike systemd[1840]: appimaged.service: Main process exited, code=exited, status=1/FAILURE
апр 14 13:28:42 Lenovo-Mike systemd[1840]: appimaged.service: Failed with result 'exit-code'.
апр 14 13:28:45 Lenovo-Mike systemd[1840]: appimaged.service: Scheduled restart job, restart counter is at 2259.
апр 14 13:28:45 Lenovo-Mike systemd[1840]: Stopped AppImage system integration daemon.
```
Linux Mint 21.1 Vera x64
Linux kernel 5.15.0-69

### PR DESCRIPTION
**Pull request by CalebQ42**
A simple fix for #251 by replacing `log.Fatal` in a few places with `log.Println`.

### CODE REVIEW

**Comment by probonopd** [comment]
This would allow the program to continue (in a broken state) but doesn't really fix the issue that causes the malfunction.

**Comment by probonopd** [comment]
@CalebQ42 would you agree that it is better to not run at all rather than to run in a half-working state?

**Comment by CalebQ42** [comment]
For me it comes down to 2 main reasons that it would be fine the ignore the error in this instance:

1. The problem (at least in #251) is not originating in `appimaged`, but instead with the external service (zeroconf) which we have minimal control over.
2. I honestly haven't done that much research and investigation on what exactly the zeroconf is needed for, but from what I can tell the error does not largely impact the core functionality of `appimaged`.

Ultimately this is similar to your decision to not add configuration to `appimaged` where you end up with multiple different setups that can each have their own quirks and problems. Though I might disagree with it, it is a 100% valid decision that I will happily follow since it is your project.

Sorry if this isn't very elegantly put, I'm fairly sleep deprived ATM, lol.

**Comment by probonopd** [comment]
You are right in that we are currently not yet making use of zeroconf. It is something I wanted to do but never came around to doing so far. The idea was that appimaged instances on the local network would find each other, and AppImages could be exchanged/updated over the network "automagically".

Instead of leaving this in a half-working state, I think the cleaner option would be to comment out Zeroconf entirely for now, until we really start making use of it.

**Pull request merged**
