### PR TITLE
Prevent loop of unsuccessfull attempts (invalid cross-device link) to…

### PR DESCRIPTION
**Pull request by eMPee584**
… move desktop file when user's cache directory lies on a tmpfs mount (unburden-home-dir set up to minimize flash writes)

appimaged: 2020/11/29 19:33:24 Registering AppImages in [/home/user/Downloads /home/user/Desktop /home/user/Applications /opt /usr/local/bin]
appimaged: 2020/11/29 ERROR main: rename /home/user/.cache/applications//appimagekit_6f9acfe2118f26ccc7b52fb34e248f97.desktop /home/user/.local/share/applications/appimagekit_6f9acfe2118f26ccc7b52fb34e248f97.desktop: invalid cross-device link
appimaged: 2020/11/29 19:33:27 main: Moved 1 desktop files to /home/user/.local/share/applications/; use -v to see details
appimaged: 2020/11/29 19:33:27 Desktop notification:  Added application
appimaged: 2020/11/29 19:33:27 Ran update-desktop-database /home/user/.local/share/applications/

This of course is a bit impromptu again.. :sweat_smile: #lazy

### CODE REVIEW

**Comment by probonopd** [comment]
Thanks @eMPee584. I am a bit hesitant to add a dependency to a gist. Could you please integrate the code into this repo?

Thank you very much.

**Comment by eMPee584** [comment]
Ok here's an easier workaround.. the CI borks though.

**Comment by probonopd** [comment]
```
github.com/otiai10/copy/stat_times.go:17:29: cannot use stat.Atim.Sec (type int32) as type int64 in argument to time.Unix
github.com/otiai10/copy/stat_times.go:17:44: cannot use stat.Atim.Nsec (type int32) as type int64 in argument to time.Unix
github.com/otiai10/copy/stat_times.go:18:29: cannot use stat.Ctim.Sec (type int32) as type int64 in argument to time.Unix
github.com/otiai10/copy/stat_times.go:18:44: cannot use stat.Ctim.Nsec (type int32) as type int64 in argument to time.Unix
```

Seems to be blocked by https://github.com/otiai10/copy/pull/39

**Comment by probonopd** [comment]
Now that https://github.com/otiai10/copy/pull/41 is fixed thanks to @CalebQ42, can we revive this?

**Comment by probonopd** [comment]
```
Error: ../src/appimaged/appimaged.go:261:23: undefined: files
Error: Process completed with exit code 2.
```

**Comment by probonopd** [comment]
@CalebQ42 wdyt?

**Comment by CalebQ42** [comment]
I don't think we really need this rename anymore. Since we get the desktop file from the AppImage then edited in memory, we don't need to worry about a ton of writes causing the application menu to reload a bunch of times. All that would need to be done is changing the initial desktop file write to `xdg.DataHome` instead of `xdg.CacheHome` and removing this rename.

**Comment by probonopd** [comment]
Closing in favor of #222. Thank you very much.

**Pull request closed without merging**
