### PR TITLE
Move from Travis CI to GitHub actions

### PR DESCRIPTION
**Pull request by srevinsaju**

### CODE REVIEW

**Comment by srevinsaju** [comment]
@probonopd kindly review

**Comment by probonopd** [comment]
Thank you very much @srevinsaju. Why did you remove `-X main.commit=$COMMIT"` and what is supposed to replace it?

**Comment by srevinsaju** [comment]
oh might have missed that. Thanks!

**Comment by srevinsaju** [comment]
@probonopd fixed on https://github.com/probonopd/go-appimage/pull/109/commits/f27edd6e1ceb5077ea78731da757d8171833968d!

**Comment by probonopd** [comment]
Oops! Shame on me. I didn't remember this PR. So now https://github.com/probonopd/go-appimage/commit/9e00f9ea1009c0772c265a5f556ff6169b6048ca basically implements a similar thing. Apparently @CalebQ42 missed this PR as well, as did I. Sorry! I hope the solution implemented now works well for you -- if not, please let's know.

**Pull request closed without merging**
